const profileFields = [
  {
    labelText: 'First Name',
    labelFor: 'first-name',
    id: 'firstname',
    name: 'firstName',
    type: 'text',
    autoComplete: 'firstname',
    isRequired: true,
    placeholder: 'Enter your First Name',
  },
  {
    labelText: 'Last Name',
    labelFor: 'lastname',
    id: 'lastname',
    name: 'lastName',
    type: 'text',
    autoComplete: 'lastname',
    isRequired: true,
    placeholder: 'Enter your Last Name',
  },
  {
    labelText: 'Address',
    labelFor: 'address',
    id: 'address',
    name: 'address',
    type: 'text',
    autoComplete: 'address',
    isRequired: false,
    placeholder: 'Enter your address',
  },
  {
    labelText: 'City',
    labelFor: 'city',
    id: 'city',
    name: 'city',
    type: 'text',
    autoComplete: 'city',
    isRequired: false,
    placeholder: 'Enter the City where you live',
  },
  // {
  //   labelText: 'Telephone',
  //   labelFor: 'telephone',
  //   id: 'telephone',
  //   name: 'phoneNumber',
  //   type: 'phone',
  //   autoComplete: 'telephone',
  //   isRequired: false,
  //   placeholder: 'Your Telephone Number',
  // },
  {
    labelText: 'Github Username',
    labelFor: 'github-username',
    id: 'github-username',
    name: 'githubUsername',
    type: 'text',
    autoComplete: 'github-username',
    isRequired: false,
    placeholder: 'Your Github Username',
  },
];

export const passwordFields = [
  {
    labelText: 'Current Password',
    labelFor: 'current-password',
    id: 'current-password',
    name: 'current-password',
    type: 'passsword',
    autoComplete: 'current-password',
    isRequired: true,
    placeholder: 'Enter your current password',
  },
  {
    labelText: 'New Password',
    labelFor: 'new-password',
    id: 'new-password',
    name: 'new-password',
    type: 'password',
    autoComplete: 'new-password',
    isRequired: true,
    placeholder: 'Enter new password',
  },
  {
    labelText: 'Confirm Password',
    labelFor: 'confirm-password',
    id: 'confirm-password',
    name: 'confirm-password',
    type: 'password',
    autoComplete: 'confirm-password',
    isRequired: true,
    placeholder: 'Re-enter the new password',
  },
];

export default profileFields;
