name: CI
on:
  # Triggers the workflow on push for all branches
  push:
  # Triggered also on pull request against the develop and main branch
  pull_request:
    branches:
      - main
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: test_environment
    env:
      BACKEND_URL: http://localhost:4000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install all dependencies
        run: npm install
      - name: Check linting errors
        run: npm run lint
      - name: Run tests and generate coverage reports
        run: npm run coverage
      - name: Sending coveralls report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
